var deck = [
	{ color: null, number: null, name: 'choose color', action: ['change_color'] },
	{ color: null, number: null, name: 'choose color', action: ['change_color'] },
	{ color: null, number: null, name: 'choose color', action: ['change_color'] },
	{ color: null, number: null, name: 'choose color', action: ['change_color'] },
	
	{ color: null, number: null, name: 'four_cards', action: ['four_cards', 'change_color'] },
	{ color: null, number: null, name: 'four_cards', action: ['four_cards', 'change_color'] },
	{ color: null, number: null, name: 'four_cards', action: ['four_cards', 'change_color'] },
	{ color: null, number: null, name: 'four_cards', action: ['four_cards', 'change_color'] },

	{ color: 'green', number: 0, name: 0, action: null },
	{ color: 'green', number: 1, name: 1, action: null },
	{ color: 'green', number: 1, name: 1, action: null },
	{ color: 'green', number: 2, name: 2, action: null },
	{ color: 'green', number: 2, name: 2, action: null },
	{ color: 'green', number: 3, name: 3, action: null },
	{ color: 'green', number: 3, name: 3, action: null },
	{ color: 'green', number: 4, name: 4, action: null },
	{ color: 'green', number: 4, name: 4, action: null },
	{ color: 'green', number: 5, name: 5, action: null },
	{ color: 'green', number: 5, name: 5, action: null },
	{ color: 'green', number: 6, name: 6, action: null },
	{ color: 'green', number: 6, name: 6, action: null },
	{ color: 'green', number: 7, name: 7, action: null },
	{ color: 'green', number: 7, name: 7, action: null },
	{ color: 'green', number: 8, name: 8, action: null },
	{ color: 'green', number: 8, name: 8, action: null },
	{ color: 'green', number: 9, name: 9, action: null },
	{ color: 'green', number: 9, name: 9, action: null },

	{ color: 'red', number: 0, name: 0, action: null },
	{ color: 'red', number: 1, name: 1, action: null },
	{ color: 'red', number: 1, name: 1, action: null },
	{ color: 'red', number: 2, name: 2, action: null },
	{ color: 'red', number: 2, name: 2, action: null },
	{ color: 'red', number: 3, name: 3, action: null },
	{ color: 'red', number: 3, name: 3, action: null },
	{ color: 'red', number: 4, name: 4, action: null },
	{ color: 'red', number: 4, name: 4, action: null },
	{ color: 'red', number: 5, name: 5, action: null },
	{ color: 'red', number: 5, name: 5, action: null },
	{ color: 'red', number: 6, name: 6, action: null },
	{ color: 'red', number: 6, name: 6, action: null },
	{ color: 'red', number: 7, name: 7, action: null },
	{ color: 'red', number: 7, name: 7, action: null },
	{ color: 'red', number: 8, name: 8, action: null },
	{ color: 'red', number: 8, name: 8, action: null },
	{ color: 'red', number: 9, name: 9, action: null },
	{ color: 'red', number: 9, name: 9, action: null },

	{ color: 'blue', number: 0, name: 0, action: null },
	{ color: 'blue', number: 1, name: 1, action: null },
	{ color: 'blue', number: 1, name: 1, action: null },
	{ color: 'blue', number: 2, name: 2, action: null },
	{ color: 'blue', number: 2, name: 2, action: null },
	{ color: 'blue', number: 3, name: 3, action: null },
	{ color: 'blue', number: 3, name: 3, action: null },
	{ color: 'blue', number: 4, name: 4, action: null },
	{ color: 'blue', number: 4, name: 4, action: null },
	{ color: 'blue', number: 5, name: 5, action: null },
	{ color: 'blue', number: 5, name: 5, action: null },
	{ color: 'blue', number: 6, name: 6, action: null },
	{ color: 'blue', number: 6, name: 6, action: null },
	{ color: 'blue', number: 7, name: 7, action: null },
	{ color: 'blue', number: 7, name: 7, action: null },
	{ color: 'blue', number: 8, name: 8, action: null },
	{ color: 'blue', number: 8, name: 8, action: null },
	{ color: 'blue', number: 9, name: 9, action: null },
	{ color: 'blue', number: 9, name: 9, action: null },

	{ color: 'yellow', number: 0, name: 0, action: null },
	{ color: 'yellow', number: 1, name: 1, action: null },
	{ color: 'yellow', number: 1, name: 1, action: null },
	{ color: 'yellow', number: 2, name: 2, action: null },
	{ color: 'yellow', number: 2, name: 2, action: null },
	{ color: 'yellow', number: 3, name: 3, action: null },
	{ color: 'yellow', number: 3, name: 3, action: null },
	{ color: 'yellow', number: 4, name: 4, action: null },
	{ color: 'yellow', number: 4, name: 4, action: null },
	{ color: 'yellow', number: 5, name: 5, action: null },
	{ color: 'yellow', number: 5, name: 5, action: null },
	{ color: 'yellow', number: 6, name: 6, action: null },
	{ color: 'yellow', number: 6, name: 6, action: null },
	{ color: 'yellow', number: 7, name: 7, action: null },
	{ color: 'yellow', number: 7, name: 7, action: null },
	{ color: 'yellow', number: 8, name: 8, action: null },
	{ color: 'yellow', number: 8, name: 8, action: null },
	{ color: 'yellow', number: 9, name: 9, action: null },
	{ color: 'yellow', number: 9, name: 9, action: null },
];